# This file was generated by GoReleaser. DO NOT EDIT.
cask "oclai" do
  name "oclai"
  desc "An AI powered terminal assistant similar to Claude Code and Gemini CLI, but runs entirely offline using local models. No API keys, no subscriptions, no data leaving your machine."
  homepage "https://github.com/thejasmeetsingh/oclai"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oclai"

  on_macos do
    on_intel do
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v#{version}/oclai_#{version}_Darwin_x86_64.tar.gz"
      sha256 "9f1baa87ad749c81ccd83a9a8346233ce470bb546d7ac4d706c266e359ab7092"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v#{version}/oclai_#{version}_Darwin_arm64.tar.gz"
      sha256 "e32a4cbb0fe311c7dc50bc39f1c6d689ab19796b5dd0303fa475d8b1e14eb171"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v#{version}/oclai_#{version}_Linux_x86_64.tar.gz"
      sha256 "c65a73b94f56ab68bff062703316746786d80cd6141f1e900fbec40e44cbeac1"
    end
    on_arm do
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v#{version}/oclai_#{version}_Linux_arm64.tar.gz"
      sha256 "6afe69b5b2a5bb82934139304113bd8b80091c6bf4fdef9a78e7e09bf2858492"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oclai"]
    end
  end

  zap trash: [
      "~/.oclai",
      "~/Library/Caches/oclai",
    ]

end
