# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oclai < Formula
  desc "An AI powered terminal assistant similar to Claude Code and Gemini CLI, but runs entirely offline using local models. No API keys, no subscriptions, no data leaving your machine."
  homepage "https://github.com/thejasmeetsingh/oclai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v1.0.0/oclai_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "23d50143e8622e27c05e09c00ff99690cfeac226e31956f6d971a252f8fee566"

      def install
        bin.install "oclai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v1.0.0/oclai_1.0.0_Darwin_arm64.tar.gz"
      sha256 "616d1d77e451c9304f3f55910f58c881593eeb5fdc4e09555245bac49b360a9c"

      def install
        bin.install "oclai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v1.0.0/oclai_1.0.0_Linux_x86_64.tar.gz"
      sha256 "7c54b2243f7de541bbaa6265a9d588d119cd8d603fbfa38249be1f1162b4d404"
      def install
        bin.install "oclai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thejasmeetsingh/oclai/releases/download/v1.0.0/oclai_1.0.0_Linux_arm64.tar.gz"
      sha256 "989eccd407fd9b69769231a17990445d9ec44ace95cedca4b3e2ab5161ccf45c"
      def install
        bin.install "oclai"
      end
    end
  end

  test do
    system "#{bin}/oclai", "--version"
  end
end
